### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by iseolin76** [theMomentTeam/the_moment_client#46]
- [x] api 상세 연결
- [x] modal 상태관리
- [x] modal 안 눌렀을 때 모달 꺼짐 수정
- [x] 디자인 패턴 적용
